apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kafka
  name: kafka-config
  labels:
    app: kafka
data:
  kafka_server_jaas.conf: |-
    KafkaServer {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="admin"
      password="&JD@dsd"
      user_admin="&JD@dsd"
      user_producer="prod-crie"
      user_consumer="cons-crie";
    };
    KafkaClient {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="producer"
      password="prod-crie"
    }
    Client {
      org.apache.zookeeper.server.auth.DigestLoginModule required
      username="kafka"
      password="kafka";
    };
