---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-eagle
  namespace: kafka
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-eagle
      app.kubernetes.io/component: kafka-eagle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-eagle
        app.kubernetes.io/component: kafka-eagle
    spec:
      imagePullSecrets:
        - name: dockersecret
      containers:
        - image: 197.6.2.10:5000/buzhiyun/kafka-eagle:latest
          imagePullPolicy: Always
          name: kafka-eagle
          ports:
            - containerPort: 8048
              name: 8048tcp01
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /opt/kafka-eagle/conf
              name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 256
            name: kafka-eagle-config
            optional: false
          name: conf
