apiVersion: v1
kind: Service
metadata:
  namespace: ems
  name: elasticsearch-client
  labels:
    app: elasticsearch
    role: client
spec:
  ports:
    - port: 9200
      name: client
      nodePort: 9200
    - port: 9300
      name: transport
  selector:
    app: elasticsearch
    role: client
  type: NodePort
