apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: kafka
  labels:
    app: kafka-manager
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9000
      targetPort: 9000
      nodePort: 30900
  selector:
    app: kafka-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka
  labels:
    app: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      imagePullSecrets:
        - name: dockersecret
      containers:
        - name: kafka-manager
          image: 197.6.2.10:5000/zenko/kafka-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka-manager
              containerPort: 9000
              protocol: TCP
          env:
            - name: ZK_HOSTS
              value: "zookeeper-0.zookeeper-hs:2181,zookeeper-1.zookeeper-hs:2181,zookeeper-2.zookeeper-hs:2181"
          livenessProbe:
            httpGet:
              path: /api/health
              port: kafka-manager
          readinessProbe:
            httpGet:
              path: /api/health
              port: kafka-manager
