apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30093
      name: server
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
